### PR TITLE
refactor(remove-item-prop): removed item prop in favor of indexOf

### PR DESCRIPTION
**Pull request by souporserious**
**What**:
Related to https://github.com/paypal/react-autocompletely/issues/63

**Why**:
Just trying to keep the API small if we can :)

**How**:
Removed the index prop in favor of a method in autocomplete that uses the instance and `indexOf` to determine the items index.

**Checklist**:

- [x] Documentation
- [x] Tests
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

If this looks good, just let me know and I will update all of the examples 😎

### CODE REVIEW

**Comment by kentcdodds** [comment]
I remember trying to do this and there was a problem with when things get resorted (the index of item instances doesn't change, but the order of them in the DOM does). If you sift through the recording you'll see when I had to deal with this problem. `index` must stay I'm afraid.

**Comment by souporserious** [comment]
Dang 😞 I totally remember now. Any ideas on how to handle sections and passing the `index` easier? I'm working with something like this..

```
<Select>
  <Optgroup>
    <Option index={0}>...</Option>
    <Option index={1}>...</Option>
  </Optgroup>
  <Optgroup>
    <Option index={2}>...</Option>
    <Option index={3}>...</Option>
  </Optgroup>
</Select>
```

**Comment by kentcdodds** [comment]
What if we make it optional? Might be a footgun though... 🤔

**Comment by souporserious** [comment]
If you use `index` as your key I think it will always be in the same spot 🤔 could we remove the need for it and somehow require your key to be an index?

**Comment by kentcdodds** [comment]
Unfortunately, react doesn't give us access to the `key` prop we put on elements (similar to the `ref` prop). So we can't access that :-(

**Comment by souporserious** [comment]
Dang. Maybe making the `index` optional like you said and mentioning in the docs how controlling it yourself is beneficial in some cases might work?

**Pull request closed without merging**
