### PR TITLE
completed example with material style

### PR DESCRIPTION
**Pull request by nndung179**
this example contains:
+ material style
+ styled-components
+ separate auto complete component into sub components in different files

### CODE REVIEW

**Comment by nndung179** [comment]
Hi @kentcdodds,

Please help me to review this PR.

Thank you!

**Comment by nndung179** [comment]
Hi @kentcdodds 

Please help me to review this PR

**Comment by kentcdodds** [comment]
Awesome! Thanks so much for this! As mentioned in #1, we're moving examples over to codesandbox.io. You can for [this one](http://kcd.im/rac-example) and make your example there instead. That should make things a little easier. Then you can update the README here with a link to yours. Would you mind doing that?

**Comment by nndung179** [comment]
Hi @kentcdodds 

Nice buddy, That is exactly what I expected. I will move it into it. Thank you!

**Comment by nndung179** [comment]
Hi @kentcdodds 

Here is a link of demo: [https://codesandbox.io/s/gOmNGvN6](https://codesandbox.io/s/gOmNGvN6)

**Comment by nndung179** [comment]
@kentcdodds I just updated readme as well.

**Comment by nndung179** [comment]
I wonder if I can create a new repo and update readme. Because look like the example should not be merged like the way you said. Only accept link & readme at this moment, right?

**Comment by kentcdodds** [comment]
Yeah, at the moment, we're only accepting README updates to the list of examples :smile:

Really would appreciate any feedback on the API that you have. How could it be improved?

**Comment by nndung179** [comment]
I just added new repo replace for this. Please help me to close this PR. 

Thank you!

**Pull request closed without merging**
